export const listOfDrugs = [
  'Advil',
  'Tylenol',
  'Aspirin',
  'Aleve',
  'Benadryl',
  'Claritin',
  'Zyrtec',
  'Robitussin',
  'Mucinex',
  'Pepto-Bismol',
  'Acetaminophen',
  'Adderall',
  'Amitriptyline',
  'Amlodipine',
  'Amoxicillin',
  'Ativan',
  'Atorvastatin',
  'Azithromycin',
  'Benzonatate',
  'Brilinta',
  'Bunavail',
  'Buprenorphine',
  'Cepacol Antibacterial',
  'Cephalexin',
  'Childrens Dimetapp',
  'Ciprofloxacin',
  'Citalopram',
  'Clindamycin',
  'Clonazepam',
  'Cortaid',
  'Cyclobenzaprine',
  'Cymbalta',
  'Doxycycline',
  'Dupixent',
  'Entresto',
  'Entyvio',
  'Farxiga',
  'Fentanyl Patch',
  'Gabapentin',
  'Gaviscon',
  'Gilenya',
  'Humira',
  'Hydrochlorothiazide',
  'Hydroxychloroquine',
  'Ibuprofen',
  'Imbruvica',
  'Invokana',
  'Januvia',
  'Jardiance',
  'Kevzara',
  'Lexapro',
  'Lisinopril',
  'Lofexidine',
  'Loratadine',
  'Lotrimin AF',
  'Lyrica',
  'Maalox Antacid',
  'Melatonin',
  'Meloxicam',
  'Metformin',
  'Methadone',
  'Methotrexate',
  'Metoprolol',
  'Midol',
  'Motrin IB',
  'Naloxone',
  'Naltrexone',
  'Naproxen',
  'Narcan',
  'Nurtec',
  'Omeprazole',
  'Onpattro',
  'Orajel',
  'Otezla',
  'Ozempic',
  'Pantoprazole',
  'Plan B',
  'Prednisone',
  'Probuphine',
  'Rolaids',
  'Rybelsus',
  'Sublocade',
  'Tagamet HB',
  'Tramadol',
  'Trazodone',
  'Viagra',
  'Wegovy',
  'Wellbutrin',
  'Xanax',
  'Zantac',
  'Zubsolv',
];